#!/usr/bin/env bun

/**
 * Pre-build script to bundle client assets for binary embedding
 *
 * This script bundles client TypeScript files into a single JS file
 * and prepares CSS files for embedding in the binary.
 */

import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mkdirSync, writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');
const buildDir = resolve(rootDir, '.build');
const srcAppDir = resolve(rootDir, 'src/app');

console.log('📦 Bundling assets for binary embedding...');

// Create build directory
mkdirSync(buildDir, { recursive: true });

// Bundle client loader (main entry point)
console.log('  Bundling client/islands/loader.ts...');
console.log('    This will include all statically imported dependencies:');
console.log('    - base.ts');
console.log('    - tab-navigation.ts');
console.log('    - book-detail.ts');
console.log('    - cover-image.ts');
console.log('    - shared/logger.ts');
const loaderResult = await Bun.build({
    entrypoints: [resolve(rootDir, 'client/islands/loader.ts')],
    target: 'browser',
    minify: true,
    outdir: buildDir,
});

if (!loaderResult.success) {
    console.error('❌ Failed to bundle loader:', loaderResult.logs);
    process.exit(1);
}

// Log bundled files info
console.log('  Bundle output:');
for (const output of loaderResult.outputs) {
    const size = (output.size / 1024).toFixed(2);
    console.log(`    - ${output.path} (${size} KB)`);
}

// Verify that all dependencies are bundled
const bundledCode = await loaderResult.outputs[0]?.text() ?? '';
const hasTabNavigation = bundledCode.includes('TabNavigationIsland') || bundledCode.includes('tab-navigation');
const hasBookDetail = bundledCode.includes('BookDetailIsland') || bundledCode.includes('book-detail');
const hasCoverImage = bundledCode.includes('CoverImageIsland') || bundledCode.includes('cover-image');

console.log('  Dependency check:');
console.log(`    - TabNavigationIsland: ${hasTabNavigation ? '✅' : '❌'}`);
console.log(`    - BookDetailIsland: ${hasBookDetail ? '✅' : '❌'}`);
console.log(`    - CoverImageIsland: ${hasCoverImage ? '✅' : '❌'}`);

if (!hasTabNavigation || !hasBookDetail || !hasCoverImage) {
    console.warn('⚠️  Warning: Some dependencies may not be fully bundled!');
}

// Read CSS files and generate TypeScript module
console.log('  Reading CSS files...');
const mainCss = await Bun.file(resolve(srcAppDir, 'styles/main.css')).text();
const logsCss = await Bun.file(resolve(srcAppDir, 'styles/logs.css')).text();
const variablesCss = await Bun.file(resolve(srcAppDir, 'styles/variables.css')).text();

// Read bundled loader.js
const loaderJs = await Bun.file(resolve(buildDir, 'loader.js')).text();

// Generate TypeScript file with embedded assets
const generatedTs = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/bundle-assets.ts
 */

// CSS files
export const embeddedCss: Record<string, string> = {
    'main.css': ${JSON.stringify(mainCss)},
    'logs.css': ${JSON.stringify(logsCss)},
    'variables.css': ${JSON.stringify(variablesCss)},
};

// Bundled client JavaScript
const embeddedLoaderJs = ${JSON.stringify(loaderJs)};

export function getEmbeddedClientJs(path: string): string | null {
    if (path === 'islands/loader.js') {
        return embeddedLoaderJs;
    }
    return null;
}

// No-op function for compatibility
export async function loadEmbeddedClientJs(): Promise<void> {
    // Assets are already loaded at import time
}
`;

const outputPath = resolve(srcAppDir, 'embedded-assets.generated.ts');
writeFileSync(outputPath, generatedTs, 'utf-8');

console.log('✅ Assets bundled and embedded successfully!');
console.log(`   Bundled JS: ${buildDir}/loader.js`);
console.log(`   Generated: ${outputPath}`);
